expansions = {
    "10E",
    "2ED",
    "2X2",
    "2XM",
    "3ED",
    "40K",
    "4ED",
    "5DN",
    "5ED",
    "6ED",
    "7ED",
    "8ED",
    "9ED",
    "A25",
    "AER",
    "AFC",
    "AFR",
    "AKH",
    "ALA",
    "ALL",
    "ANB",
    "APC",
    "ARB",
    "ARN",
    "ATQ",
    "AVR",
    "BBD",
    "BFZ",
    "BNG",
    "BOK",
    # "BRO",
    "C13",
    "C14",
    "C15",
    "C16",
    "C17",
    "C18",
    "C19",
    "C20",
    "C21",
    "CHK",
    "CLB",
    "CM1",
    "CMR",
    "CN2",
    "CNS",
    "CON",
    "CSP",
    "DGM",
    "DIS",
    "DKA",
    "DMC",
    "DMR",
    "DMU",
    "DOM",
    "DRK",
    "DST",
    "DTK",
    "E02",
    "ELD",
    "EMA",
    "EMN",
    "EVE",
    "EXO",
    "FEM",
    "FRF",
    "FUT",
    "GK1",
    "GK2",
    "GN2",
    "GN3",
    "GNT",
    "GPT",
    "GRN",
    "GTC",
    "HBG",
    "HML",
    "HOU",
    "ICE",
    "IKO",
    "IMA",
    "INV",
    "ISD",
    "JMP",
    "JOU",
    "JUD",
    "KHC",
    "KHM",
    "KLD",
    "KTK",
    "LEA",
    "LEB",
    "LEG",
    "LGN",
    "LRW",
    "M10",
    "M11",
    "M12",
    "M13",
    "M14",
    "M15",
    "M19",
    "M20",
    "M21",
    "MBS",
    "MH1",
    "MH2",
    "MIC",
    "MID",
    "MIR",
    "MM2",
    "MM3",
    "MMA",
    "MMQ",
    "MOR",
    "MRD",
    "NCC",
    "NEC",
    "NEM",
    "NEO",
    "NPH",
    "ODY",
    "OGW",
    "ONS",
    "ORI",
    "PCY",
    "PLC",
    "PLS",
    "RAV",
    "RIX",
    "RNA",
    "ROE",
    "RTR",
    "SCG",
    "SHM",
    "SNC",
    "SOI",
    "SOK",
    "SOM",
    "STH",
    "STX",
    "THB",
    "THS",
    "TMP",
    "TOR",
    "TSP",
    "TSR",
    "UDS",
    "ULG",
    "UMA",
    "USG",
    "VIS",
    "VOC",
    "VOW",
    "WAR",
    "WTH",
    "WWK",
    "XLN",
    "ZEN",
    "ZNC",
    "ZNR",
}

card_template = """
:mtgtip:`{card[name]}<{image}|{card_uri}>`
   {card_text}

"""

symbols_map = {
    #    '}{': '} {',
    "{E}": "|energy|",
    "{C}": "|colorless|",
    "{T}": "|tap|",
    "{Q}": "|untap|",
    "{U}": "|mana_u|",
    "{W}": "|mana_w|",
    "{G}": "|mana_g|",
    "{B}": "|mana_b|",
    "{R}": "|mana_r|",
    "{P}": "|mana_p|",
    "{S}": "|mana_s|",
    "{2/U}": "|mana_2u|",
    "{2/W}": "|mana_2w|",
    "{2/B}": "|mana_2b|",
    "{2/G}": "|mana_2g|",
    "{2/R}": "|mana_2r|",
    "{U/P}": "|mana_up|",
    "{W/P}": "|mana_wp|",
    "{B/P}": "|mana_bp|",
    "{G/P}": "|mana_gp|",
    "{R/P}": "|mana_rp|",
    "{X}": "|mana_x|",
    "{0}": "|mana_0|",
    "{1}": "|mana_1|",
    "{2}": "|mana_2|",
    "{3}": "|mana_3|",
    "{4}": "|mana_4|",
    "{5}": "|mana_5|",
    "{6}": "|mana_6|",
    "{7}": "|mana_7|",
    "{8}": "|mana_8|",
    "{9}": "|mana_9|",
    "{10}": "|mana_10|",
    "{11}": "|mana_11|",
    "{12}": "|mana_12|",
    "{13}": "|mana_13|",
    "{14}": "|mana_14|",
    "{15}": "|mana_15|",
    "{16}": "|mana_16|",
    "{20}": "|mana_20|",
    "{R/G}": "|mana_rg|",
    "{R/W}": "|mana_rw|",
    "{U/B}": "|mana_ub|",
    "{U/R}": "|mana_ur|",
    "{W/B}": "|mana_wb|",
    "{W/U}": "|mana_wu|",
    "{B/G}": "|mana_bg|",
    "{B/R}": "|mana_br|",
    "{G/W}": "|mana_gw|",
    "{G/U}": "|mana_gu|",
    "{G/U/P}": "|mana_gup|",
    "{G/W/P}": "|mana_gwp|",
    "\n": "\n\n   ",
    "||": "|\ |",
}
mtga_rev_map = {
    "|energy|": "E",
    "|colorless|": "C",
    "|tap|": "T",
    "|untap|": "Q",
    "|mana_u|": "U",
    "|mana_w|": "W",
    "|mana_g|": "G",
    "|mana_b|": "B",
    "|mana_r|": "R",
    "|mana_p|": "P",
    "|mana_s|": "Si",
    "|mana_2u|": "(2/U)",
    "|mana_2w|": "(2/W)",
    "|mana_2b|": "(2/B)",
    "|mana_2g|": "(2/G)",
    "|mana_2r|": "(2/R)",
    "|mana_up|": "(U/P)",
    "|mana_wp|": "(W/P)",
    "|mana_bp|": "(B/P)",
    "|mana_gp|": "(G/P)",
    "|mana_rp|": "(R/P)",
    "|mana_x|": "X",
    "|mana_0|": "0",
    "|mana_1|": "1",
    "|mana_2|": "2",
    "|mana_3|": "3",
    "|mana_4|": "4",
    "|mana_5|": "5",
    "|mana_6|": "6",
    "|mana_7|": "7",
    "|mana_8|": "8",
    "|mana_9|": "9",
    "|mana_10|": "10",
    "|mana_11|": "11",
    "|mana_12|": "12",
    "|mana_13|": "13",
    "|mana_14|": "14",
    "|mana_15|": "15",
    "|mana_rg|": "(R/G)",
    "|mana_rw|": "(R/W)",
    "|mana_ub|": "(U/B)",
    "|mana_ur|": "(U/R)",
    "|mana_wb|": "(W/B)",
    "|mana_wu|": "(W/U)",
    "|mana_bg|": "(B/G)",
    "|mana_br|": "(B/R)",
    "|mana_gw|": "(G/W)",
    "|mana_gu|": "(G/U)",
}
mtga_cost_map = {
    "C": "|colorless|",
    "T": "|tap|",
    "Q": "|untap|",
    "U": "|mana_u|",
    "W": "|mana_w|",
    "G": "|mana_g|",
    "B": "|mana_b|",
    "R": "|mana_r|",
    "P": "|mana_p|",
    "Si": "|mana_s|",
    "(2/U)": "|mana_2u|",
    "(2/W)": "|mana_2w|",
    "(2/B)": "|mana_2b|",
    "(2/G)": "|mana_2g|",
    "(2/R)": "|mana_2r|",
    "(U/P)": "|mana_up|",
    "(W/P)": "|mana_wp|",
    "(B/P)": "|mana_bp|",
    "(G/P)": "|mana_gp|",
    "(R/P)": "|mana_rp|",
    "X": "|mana_x|",
    "0": "|mana_0|",
    "1": "|mana_1|",
    "2": "|mana_2|",
    "3": "|mana_3|",
    "4": "|mana_4|",
    "5": "|mana_5|",
    "6": "|mana_6|",
    "7": "|mana_7|",
    "8": "|mana_8|",
    "9": "|mana_9|",
    "10": "|mana_10|",
    "11": "|mana_11|",
    "12": "|mana_12|",
    "13": "|mana_13|",
    "14": "|mana_14|",
    "15": "|mana_15|",
    "(R/G)": "|mana_rg|",
    "(R/W)": "|mana_rw|",
    "(U/B)": "|mana_ub|",
    "(U/R)": "|mana_ur|",
    "(W/B)": "|mana_wb|",
    "(W/U)": "|mana_wu|",
    "(B/G)": "|mana_bg|",
    "(B/R)": "|mana_br|",
    "(G/W)": "|mana_gw|",
    "(G/U)": "|mana_gu|",
}

cardtype_trans = [
    "0",  # 0
    "artifact",  # 1
    "creature",  # 2
    "enchantment",  # 3
    "instant",  # 4
    "land",  # 5
    "6",  # 6
    "7",  # 7
    "planeswalker",  # 8
    "9",  # 9
    "sorcery",  # 10
    "11",  # 11
    "12",  # 12
    "13",  # 13 dungeon?
]

missing_cards = {
    "Phil Foglio": [
        "https://scryfall.com/card/2x2/359/chaos-warp",
        "https://scryfall.com/card/atq/80a/mishras-factory",
        "https://scryfall.com/card/atq/80b/mishras-factory",
        "https://scryfall.com/card/atq/80c/mishras-factory",
        "https://scryfall.com/card/atq/80d/mishras-factory",
        "https://scryfall.com/card/fem/54b/goblin-chirurgeon",
        "https://scryfall.com/card/leg/251/ramirez-depietro",
        "https://scryfall.com/card/leg/287/mirror-universe",
        "https://scryfall.com/card/leg/31/presence-of-the-master",
        "https://scryfall.com/card/leg/5/cleanse",
        "https://scryfall.com/card/p02/14/bargain",
        "https://scryfall.com/card/por/66/prosperity",
        "https://scryfall.com/card/ugl/26/psychic-network",
    ],
    "Guru Lands": [
        "https://scryfall.com/card/pgru/1/plains",
        "https://scryfall.com/card/pgru/2/island",
        "https://scryfall.com/card/pgru/3/swamp",
        "https://scryfall.com/card/pgru/4/mountain",
        "https://scryfall.com/card/pgru/5/forest",
    ],
    "APAC/Euro Lands": [
        "https://scryfall.com/card/palp/10/swamp",
        "https://scryfall.com/card/palp/11/forest",
        "https://scryfall.com/card/palp/3/mountain",
        "https://scryfall.com/card/palp/4/plains",
        "https://scryfall.com/card/palp/5/swamp",
        "https://scryfall.com/card/palp/6/forest",
        "https://scryfall.com/card/palp/8/mountain",
        "https://scryfall.com/card/pelp/4/plains",
    ],
    "Arena League 2001-2003": [
        "https://scryfall.com/card/pal01/1/forest",
        "https://scryfall.com/card/pal01/11/forest",
        "https://scryfall.com/card/pal01/3/island",
        "https://scryfall.com/card/pal01/7/plains",
        "https://scryfall.com/card/pal01/9/swamp",
        "https://scryfall.com/card/pal02/1/island",
        "https://scryfall.com/card/pal03/3/swamp",
        "https://scryfall.com/card/pal03/5/forest",
    ],
    "Portal": [
        "https://scryfall.com/card/por/196/plains",
        "https://scryfall.com/card/por/197/plains",
        "https://scryfall.com/card/por/198/plains",
        "https://scryfall.com/card/por/199/plains",
        "https://scryfall.com/card/por/196s/zhs/plains",
        "https://scryfall.com/card/por/197s/zhs/plains",
        "https://scryfall.com/card/por/198s/zhs/plains",
        "https://scryfall.com/card/por/199s/zhs/plains",
        "https://scryfall.com/card/por/200s/zhs/island",
        "https://scryfall.com/card/por/201s/zhs/island",
        "https://scryfall.com/card/por/202s/zhs/island",
        "https://scryfall.com/card/por/203s/zhs/island",
        "https://scryfall.com/card/por/208s/zhs/mountain",
        "https://scryfall.com/card/por/209s/zhs/mountain",
        "https://scryfall.com/card/por/210s/zhs/mountain",
        "https://scryfall.com/card/por/211s/zhs/mountain",
        "https://scryfall.com/card/por/212s/zhs/forest",
        "https://scryfall.com/card/por/213s/zhs/forest",
        "https://scryfall.com/card/por/214s/zhs/forest",
        "https://scryfall.com/card/por/215s/zhs/forest",
    ],
    "Magic Fest": [
        "https://scryfall.com/card/pf20/2/plains",
        "https://scryfall.com/card/pf20/3/island",
        "https://scryfall.com/card/pf20/4/swamp",
        "https://scryfall.com/card/pf20/5/mountain",
        "https://scryfall.com/card/pf20/6/forest",
    ],
    "Secret Lair Drop": [
        "https://scryfall.com/card/sld/46/ja/plains",
        "https://scryfall.com/card/sld/47/ja/island",
        "https://scryfall.com/card/sld/48/ja/swamp",
        "https://scryfall.com/card/sld/49/ja/mountain",
        "https://scryfall.com/card/sld/50/ja/forest",
        "https://scryfall.com/card/sld/254/plains",
        "https://scryfall.com/card/sld/255/island",
        "https://scryfall.com/card/sld/256/swamp",
        "https://scryfall.com/card/sld/257/mountain",
        "https://scryfall.com/card/sld/258/forest",
        "https://scryfall.com/card/sld/384/swamp",
        "https://scryfall.com/card/sld/385/island",
        "https://scryfall.com/card/sld/386/island",
        "https://scryfall.com/card/sld/387/mountain",
        "https://scryfall.com/card/sld/388/forest",
        "https://scryfall.com/card/sld/389/mountain",
        "https://scryfall.com/card/sld/390/plains",
        "https://scryfall.com/card/sld/391/plains",
        "https://scryfall.com/card/sld/466/island",
        "https://scryfall.com/card/sld/476/forest",
        "https://scryfall.com/card/sld/540/plains",
        "https://scryfall.com/card/sld/541/plains",
        "https://scryfall.com/card/sld/542/plains",
        "https://scryfall.com/card/sld/543/plains",
        "https://scryfall.com/card/sld/545/plains",
        "https://scryfall.com/card/sld/547/plains",
        "https://scryfall.com/card/sld/548/island",
        "https://scryfall.com/card/sld/550/island",
        "https://scryfall.com/card/sld/553/island",
        "https://scryfall.com/card/sld/554/island",
        "https://scryfall.com/card/sld/559/swamp",
        "https://scryfall.com/card/sld/562/swamp",
        "https://scryfall.com/card/sld/564/mountain",
        "https://scryfall.com/card/sld/565/mountain",
        "https://scryfall.com/card/sld/567/mountain",
        "https://scryfall.com/card/sld/570/mountain",
        "https://scryfall.com/card/sld/574/forest",
        "https://scryfall.com/card/sld/575/forest",
        "https://scryfall.com/card/sld/576/forest",
        "https://scryfall.com/card/sld/577/forest",
        "https://scryfall.com/card/sld/578/forest",
        "https://scryfall.com/card/sld/579/forest",
        "https://scryfall.com/card/sld/690/forest",
    ],
    "Normal sets": [
        "https://scryfall.com/card/ice/371/snow-covered-island",
        "https://scryfall.com/card/csp/151/snow-covered-plains",
        "https://scryfall.com/card/usg/336/island",
        "https://scryfall.com/card/usg/345/mountain",
        "https://scryfall.com/card/mmq/331/plains",
        "https://scryfall.com/card/mmq/332/plains",
        "https://scryfall.com/card/mmq/333/plains",
        "https://scryfall.com/card/mmq/335/island",
        "https://scryfall.com/card/mmq/336/island",
        "https://scryfall.com/card/mmq/337/island",
        "https://scryfall.com/card/mmq/338/island",
        "https://scryfall.com/card/mmq/347/forest",
        "https://scryfall.com/card/mmq/348/forest",
        "https://scryfall.com/card/mmq/350/forest",
        "https://scryfall.com/card/mmq/343/mountain",
        "https://scryfall.com/card/mmq/344/mountain",
        "https://scryfall.com/card/mmq/345/mountain",
        "https://scryfall.com/card/mmq/346/mountain",
        "https://scryfall.com/card/mmq/339/swamp",
        "https://scryfall.com/card/mmq/340/swamp",
        "https://scryfall.com/card/mmq/341/swamp",
        "https://scryfall.com/card/mmq/342/swamp",
        "https://scryfall.com/card/inv/331/plains",
        "https://scryfall.com/card/inv/336/island",
        "https://scryfall.com/card/inv/337/island",
        "https://scryfall.com/card/inv/343/mountain",
        "https://scryfall.com/card/inv/345/mountain",
        "https://scryfall.com/card/inv/346/mountain",
        "https://scryfall.com/card/inv/340/swamp",
        "https://scryfall.com/card/inv/342/swamp",
        "https://scryfall.com/card/ody/331/plains",
        "https://scryfall.com/card/ody/332/plains",
        "https://scryfall.com/card/ody/333/plains",
        "https://scryfall.com/card/ody/334/plains",
        "https://scryfall.com/card/ody/336/island",
        "https://scryfall.com/card/ody/338/island",
        "https://scryfall.com/card/ody/340/swamp",
        "https://scryfall.com/card/ody/341/swamp",
        "https://scryfall.com/card/ody/342/swamp",
        "https://scryfall.com/card/ody/344/mountain",
        "https://scryfall.com/card/ody/346/mountain",
        "https://scryfall.com/card/ody/347/forest",
        "https://scryfall.com/card/ody/348/forest",
        "https://scryfall.com/card/ody/349/forest",
        "https://scryfall.com/card/ody/350/forest",
        "https://scryfall.com/card/chk/295/swamp",
        "https://scryfall.com/card/chk/297/swamp",
        "https://scryfall.com/card/chk/300/mountain",
        "https://scryfall.com/card/mrd/290/plains",
        "https://scryfall.com/card/mrd/291/island",
        "https://scryfall.com/card/mrd/292/island",
        "https://scryfall.com/card/mrd/294/island",
        "https://scryfall.com/card/mrd/295/swamp",
        "https://scryfall.com/card/mrd/297/swamp",
        "https://scryfall.com/card/mrd/301/mountain",
        "https://scryfall.com/card/mrd/305/forest",
        "https://scryfall.com/card/ons/331/plains",
        "https://scryfall.com/card/ons/340/swamp",
        "https://scryfall.com/card/ons/341/swamp",
        "https://scryfall.com/card/ons/342/swamp",
        "https://scryfall.com/card/ons/344/mountain",
        "https://scryfall.com/card/ons/345/mountain",
        "https://scryfall.com/card/ons/346/mountain",
        "https://scryfall.com/card/ons/347/forest",
        "https://scryfall.com/card/ons/348/forest",
        "https://scryfall.com/card/ons/349/forest",
        "https://scryfall.com/card/ons/350/forest",
        "https://scryfall.com/card/rav/287/plains",
        "https://scryfall.com/card/rav/291/island",
        "https://scryfall.com/card/lrw/282/plains",
        "https://scryfall.com/card/lrw/287/island",
        "https://scryfall.com/card/lrw/292/swamp",
        "https://scryfall.com/card/lrw/294/mountain",
        "https://scryfall.com/card/lrw/296/mountain",
        "https://scryfall.com/card/lrw/299/forest",
        "https://scryfall.com/card/lrw/301/forest",
        "https://scryfall.com/card/shm/286/island",
        "https://scryfall.com/card/shm/289/island",
        "https://scryfall.com/card/shm/297/mountain",
        "https://scryfall.com/card/shm/298/forest",
        "https://scryfall.com/card/shm/300/forest",
        "https://scryfall.com/card/ala/230/plains",
        "https://scryfall.com/card/ala/235/island",
        "https://scryfall.com/card/ala/236/island",
        "https://scryfall.com/card/ala/237/island",
        "https://scryfall.com/card/ala/239/swamp",
        "https://scryfall.com/card/ala/241/swamp",
        "https://scryfall.com/card/ala/247/forest",
        "https://scryfall.com/card/ala/248/forest",
        "https://scryfall.com/card/ala/249/forest",
        "https://scryfall.com/card/zen/230/plains",
        "https://scryfall.com/card/zen/231/plains",
        "https://scryfall.com/card/zen/233/plains",
        "https://scryfall.com/card/zen/236/island",
        "https://scryfall.com/card/zen/237/island",
        "https://scryfall.com/card/zen/239/swamp",
        "https://scryfall.com/card/zen/240/swamp",
        "https://scryfall.com/card/zen/242/mountain",
        "https://scryfall.com/card/zen/244/mountain",
        "https://scryfall.com/card/zen/245/mountain",
        "https://scryfall.com/card/zen/246/forest",
        "https://scryfall.com/card/zen/247/forest",
        "https://scryfall.com/card/zen/248/forest",
        "https://scryfall.com/card/roe/232/plains",
        "https://scryfall.com/card/roe/233/island",
        "https://scryfall.com/card/roe/234/island",
        "https://scryfall.com/card/roe/235/island",
        "https://scryfall.com/card/roe/236/island",
        "https://scryfall.com/card/roe/237/swamp",
        "https://scryfall.com/card/roe/238/swamp",
        "https://scryfall.com/card/roe/239/swamp",
        "https://scryfall.com/card/roe/240/swamp",
        "https://scryfall.com/card/roe/241/mountain",
        "https://scryfall.com/card/roe/242/mountain",
        "https://scryfall.com/card/roe/245/forest",
        "https://scryfall.com/card/roe/246/forest",
        "https://scryfall.com/card/roe/247/forest",
        "https://scryfall.com/card/roe/248/forest",
        "https://scryfall.com/card/som/230/plains",
        "https://scryfall.com/card/som/231/plains",
        "https://scryfall.com/card/som/234/island",
        "https://scryfall.com/card/som/235/island",
        "https://scryfall.com/card/som/236/island",
        "https://scryfall.com/card/som/237/island",
        "https://scryfall.com/card/som/239/swamp",
        "https://scryfall.com/card/som/243/mountain",
        "https://scryfall.com/card/som/244/mountain",
        "https://scryfall.com/card/som/245/mountain",
        "https://scryfall.com/card/som/246/forest",
        "https://scryfall.com/card/som/248/forest",
        "https://scryfall.com/card/mbs/146/plains",
        "https://scryfall.com/card/mbs/147/plains",
        "https://scryfall.com/card/mbs/150/swamp",
        "https://scryfall.com/card/mbs/151/swamp",
        "https://scryfall.com/card/mbs/152/mountain",
        "https://scryfall.com/card/mbs/154/forest",
        "https://scryfall.com/card/mbs/155/forest",
        "https://scryfall.com/card/nph/166/plains",
        "https://scryfall.com/card/nph/167/plains",
        "https://scryfall.com/card/nph/168/island",
        "https://scryfall.com/card/nph/169/island",
        "https://scryfall.com/card/nph/170/swamp",
        "https://scryfall.com/card/nph/171/swamp",
        "https://scryfall.com/card/nph/172/mountain",
        "https://scryfall.com/card/nph/174/forest",
        "https://scryfall.com/card/nph/175/forest",
        "https://scryfall.com/card/isd/250/plains",
        "https://scryfall.com/card/isd/252/plains",
        "https://scryfall.com/card/isd/253/island",
        "https://scryfall.com/card/isd/255/island",
        "https://scryfall.com/card/isd/257/swamp",
        "https://scryfall.com/card/isd/258/swamp",
        "https://scryfall.com/card/isd/259/mountain",
        "https://scryfall.com/card/isd/261/mountain",
        "https://scryfall.com/card/isd/263/forest",
        "https://scryfall.com/card/isd/264/forest",
        "https://scryfall.com/card/avr/230/plains",
        "https://scryfall.com/card/avr/231/plains",
        "https://scryfall.com/card/avr/233/island",
        "https://scryfall.com/card/avr/234/island",
        "https://scryfall.com/card/avr/237/swamp",
        "https://scryfall.com/card/avr/238/swamp",
        "https://scryfall.com/card/avr/239/mountain",
        "https://scryfall.com/card/avr/240/mountain",
        "https://scryfall.com/card/avr/243/forest",
        "https://scryfall.com/card/rtr/267/mountain",
        "https://scryfall.com/card/ths/234/island",
        "https://scryfall.com/card/ths/235/island",
        "https://scryfall.com/card/frf/179/island",
        "https://scryfall.com/card/frf/180/swamp",
        "https://scryfall.com/card/bfz/250/plains",
        "https://scryfall.com/card/bfz/271/forest",
        "https://scryfall.com/card/bfz/274/forest",
        "https://scryfall.com/card/ust/212/plains",
        "https://scryfall.com/card/ust/213/island",
        "https://scryfall.com/card/ust/214/swamp",
        "https://scryfall.com/card/ust/215/mountain",
        "https://scryfall.com/card/ust/216/forest",
        "https://scryfall.com/card/khm/277/snow-covered-plains",
        "https://scryfall.com/card/khm/278/snow-covered-island",
        "https://scryfall.com/card/khm/279/snow-covered-island",
        "https://scryfall.com/card/khm/280/snow-covered-swamp",
        "https://scryfall.com/card/khm/281/snow-covered-swamp",
        "https://scryfall.com/card/khm/282/snow-covered-mountain",
        "https://scryfall.com/card/khm/283/snow-covered-mountain",
        "https://scryfall.com/card/khm/285/snow-covered-forest",
        "https://scryfall.com/card/znr/266/plains",
        "https://scryfall.com/card/znr/267/plains",
        "https://scryfall.com/card/znr/268/plains",
        "https://scryfall.com/card/znr/269/island",
        "https://scryfall.com/card/znr/270/island",
        "https://scryfall.com/card/znr/271/island",
        "https://scryfall.com/card/znr/272/swamp",
        "https://scryfall.com/card/znr/273/swamp",
        "https://scryfall.com/card/znr/274/swamp",
        "https://scryfall.com/card/znr/275/mountain",
        "https://scryfall.com/card/znr/276/mountain",
        "https://scryfall.com/card/znr/277/mountain",
        "https://scryfall.com/card/znr/278/forest",
        "https://scryfall.com/card/znr/279/forest",
        "https://scryfall.com/card/znr/280/forest",
        "https://scryfall.com/card/thb/250/plains",
        "https://scryfall.com/card/thb/251/island",
        "https://scryfall.com/card/thb/252/swamp",
        "https://scryfall.com/card/thb/253/mountain",
        "https://scryfall.com/card/thb/254/forest",
        "https://scryfall.com/card/2xm/373/plains",
        "https://scryfall.com/card/2xm/374/plains",
        "https://scryfall.com/card/2xm/375/island",
        "https://scryfall.com/card/2xm/376/island",
        "https://scryfall.com/card/2xm/377/swamp",
        "https://scryfall.com/card/2xm/378/swamp",
        "https://scryfall.com/card/2xm/379/mountain",
        "https://scryfall.com/card/2xm/380/mountain",
        "https://scryfall.com/card/2xm/381/forest",
        "https://scryfall.com/card/2xm/382/forest",
        "https://scryfall.com/card/snc/272/plains",
        "https://scryfall.com/card/snc/273/plains",
        "https://scryfall.com/card/snc/274/island",
        "https://scryfall.com/card/snc/275/island",
        "https://scryfall.com/card/snc/276/swamp",
        "https://scryfall.com/card/snc/277/swamp",
        "https://scryfall.com/card/snc/279/mountain",
        "https://scryfall.com/card/snc/280/forest",
        "https://scryfall.com/card/snc/281/forest",
        "https://scryfall.com/card/unf/235/plains",
        "https://scryfall.com/card/unf/236/island",
        "https://scryfall.com/card/unf/237/swamp",
        "https://scryfall.com/card/unf/238/mountain",
        "https://scryfall.com/card/unf/239/forest",
        "https://scryfall.com/card/unf/240/plains",
        "https://scryfall.com/card/unf/241/island",
        "https://scryfall.com/card/unf/242/swamp",
        "https://scryfall.com/card/unf/243/mountain",
        "https://scryfall.com/card/unf/244/forest",
        "https://scryfall.com/card/dmu/277/plains",
        "https://scryfall.com/card/dmu/280/mountain",
    ],
}
