expansions = {
    "10E",
    "2ED",
    "2X2",
    "2XM",
    "3ED",
    "40K",
    "4ED",
    "5DN",
    "5ED",
    "6ED",
    "7ED",
    "8ED",
    "9ED",
    "A25",
    "AER",
    "AFC",
    "AFR",
    "AKH",
    "ALA",
    "ALL",
    "ANB",
    "APC",
    "ARB",
    "ARN",
    "ATQ",
    "AVR",
    "BBD",
    "BFZ",
    "BNG",
    "BOK",
    "BRO",
    "C13",
    "C14",
    "C15",
    "C16",
    "C17",
    "C18",
    "C19",
    "C20",
    "C21",
    "CHK",
    "CLB",
    "CM1",
    "CMR",
    "CN2",
    "CNS",
    "CON",
    "CSP",
    "DGM",
    "DIS",
    "DKA",
    "DMC",
    "DMU",
    "DOM",
    "DRK",
    "DST",
    "DTK",
    "E02",
    "ELD",
    "EMA",
    "EMN",
    "EVE",
    "EXO",
    "FEM",
    "FRF",
    "FUT",
    "GK1",
    "GK2",
    "GN2",
    "GN3",
    "GNT",
    "GPT",
    "GRN",
    "GTC",
    "HBG",
    "HML",
    "HOU",
    "ICE",
    "IKO",
    "IMA",
    "INV",
    "ISD",
    "JMP",
    "JOU",
    "JUD",
    "KHC",
    "KHM",
    "KLD",
    "KTK",
    "LEA",
    "LEB",
    "LEG",
    "LGN",
    "LRW",
    "M10",
    "M11",
    "M12",
    "M13",
    "M14",
    "M15",
    "M19",
    "M20",
    "M21",
    "MBS",
    "MH1",
    "MH2",
    "MIC",
    "MID",
    "MIR",
    "MM2",
    "MM3",
    "MMA",
    "MMQ",
    "MOR",
    "MRD",
    "NCC",
    "NEC",
    "NEM",
    "NEO",
    "NPH",
    "ODY",
    "OGW",
    "ONS",
    "ORI",
    "PCY",
    "PLC",
    "PLS",
    "RAV",
    "RIX",
    "RNA",
    "ROE",
    "RTR",
    "SCG",
    "SHM",
    "SNC",
    "SOI",
    "SOK",
    "SOM",
    "STH",
    "STX",
    "THB",
    "THS",
    "TMP",
    "TOR",
    "TSP",
    "TSR",
    "UDS",
    "ULG",
    "UMA",
    "USG",
    "VIS",
    "VOC",
    "VOW",
    "WAR",
    "WTH",
    "WWK",
    "XLN",
    "ZEN",
    "ZNC",
    "ZNR",
}

card_template = """
:mtgtip:`{card[name]}<{image}|{card_uri}>`
   {card_text}

"""

symbols_map = {
    #    '}{': '} {',
    "{E}": "|energy|",
    "{C}": "|colorless|",
    "{T}": "|tap|",
    "{Q}": "|untap|",
    "{U}": "|mana_u|",
    "{W}": "|mana_w|",
    "{G}": "|mana_g|",
    "{B}": "|mana_b|",
    "{R}": "|mana_r|",
    "{P}": "|mana_p|",
    "{S}": "|mana_s|",
    "{2/U}": "|mana_2u|",
    "{2/W}": "|mana_2w|",
    "{2/B}": "|mana_2b|",
    "{2/G}": "|mana_2g|",
    "{2/R}": "|mana_2r|",
    "{U/P}": "|mana_up|",
    "{W/P}": "|mana_wp|",
    "{B/P}": "|mana_bp|",
    "{G/P}": "|mana_gp|",
    "{R/P}": "|mana_rp|",
    "{X}": "|mana_x|",
    "{0}": "|mana_0|",
    "{1}": "|mana_1|",
    "{2}": "|mana_2|",
    "{3}": "|mana_3|",
    "{4}": "|mana_4|",
    "{5}": "|mana_5|",
    "{6}": "|mana_6|",
    "{7}": "|mana_7|",
    "{8}": "|mana_8|",
    "{9}": "|mana_9|",
    "{10}": "|mana_10|",
    "{11}": "|mana_11|",
    "{12}": "|mana_12|",
    "{13}": "|mana_13|",
    "{14}": "|mana_14|",
    "{15}": "|mana_15|",
    "{16}": "|mana_16|",
    "{20}": "|mana_20|",
    "{R/G}": "|mana_rg|",
    "{R/W}": "|mana_rw|",
    "{U/B}": "|mana_ub|",
    "{U/R}": "|mana_ur|",
    "{W/B}": "|mana_wb|",
    "{W/U}": "|mana_wu|",
    "{B/G}": "|mana_bg|",
    "{B/R}": "|mana_br|",
    "{G/W}": "|mana_gw|",
    "{G/U}": "|mana_gu|",
    "{G/U/P}": "|mana_gup|",
    "{G/W/P}": "|mana_gwp|",
    "\n": "\n\n   ",
    "||": "|\ |",
}
mtga_rev_map = {
    "|energy|": "E",
    "|colorless|": "C",
    "|tap|": "T",
    "|untap|": "Q",
    "|mana_u|": "U",
    "|mana_w|": "W",
    "|mana_g|": "G",
    "|mana_b|": "B",
    "|mana_r|": "R",
    "|mana_p|": "P",
    "|mana_s|": "Si",
    "|mana_2u|": "(2/U)",
    "|mana_2w|": "(2/W)",
    "|mana_2b|": "(2/B)",
    "|mana_2g|": "(2/G)",
    "|mana_2r|": "(2/R)",
    "|mana_up|": "(U/P)",
    "|mana_wp|": "(W/P)",
    "|mana_bp|": "(B/P)",
    "|mana_gp|": "(G/P)",
    "|mana_rp|": "(R/P)",
    "|mana_x|": "X",
    "|mana_0|": "0",
    "|mana_1|": "1",
    "|mana_2|": "2",
    "|mana_3|": "3",
    "|mana_4|": "4",
    "|mana_5|": "5",
    "|mana_6|": "6",
    "|mana_7|": "7",
    "|mana_8|": "8",
    "|mana_9|": "9",
    "|mana_10|": "10",
    "|mana_11|": "11",
    "|mana_12|": "12",
    "|mana_13|": "13",
    "|mana_14|": "14",
    "|mana_15|": "15",
    "|mana_rg|": "(R/G)",
    "|mana_rw|": "(R/W)",
    "|mana_ub|": "(U/B)",
    "|mana_ur|": "(U/R)",
    "|mana_wb|": "(W/B)",
    "|mana_wu|": "(W/U)",
    "|mana_bg|": "(B/G)",
    "|mana_br|": "(B/R)",
    "|mana_gw|": "(G/W)",
    "|mana_gu|": "(G/U)",
}
mtga_cost_map = {
    "C": "|colorless|",
    "T": "|tap|",
    "Q": "|untap|",
    "U": "|mana_u|",
    "W": "|mana_w|",
    "G": "|mana_g|",
    "B": "|mana_b|",
    "R": "|mana_r|",
    "P": "|mana_p|",
    "Si": "|mana_s|",
    "(2/U)": "|mana_2u|",
    "(2/W)": "|mana_2w|",
    "(2/B)": "|mana_2b|",
    "(2/G)": "|mana_2g|",
    "(2/R)": "|mana_2r|",
    "(U/P)": "|mana_up|",
    "(W/P)": "|mana_wp|",
    "(B/P)": "|mana_bp|",
    "(G/P)": "|mana_gp|",
    "(R/P)": "|mana_rp|",
    "X": "|mana_x|",
    "0": "|mana_0|",
    "1": "|mana_1|",
    "2": "|mana_2|",
    "3": "|mana_3|",
    "4": "|mana_4|",
    "5": "|mana_5|",
    "6": "|mana_6|",
    "7": "|mana_7|",
    "8": "|mana_8|",
    "9": "|mana_9|",
    "10": "|mana_10|",
    "11": "|mana_11|",
    "12": "|mana_12|",
    "13": "|mana_13|",
    "14": "|mana_14|",
    "15": "|mana_15|",
    "(R/G)": "|mana_rg|",
    "(R/W)": "|mana_rw|",
    "(U/B)": "|mana_ub|",
    "(U/R)": "|mana_ur|",
    "(W/B)": "|mana_wb|",
    "(W/U)": "|mana_wu|",
    "(B/G)": "|mana_bg|",
    "(B/R)": "|mana_br|",
    "(G/W)": "|mana_gw|",
    "(G/U)": "|mana_gu|",
}

cardtype_trans = [
    "0",  # 0
    "artifact",  # 1
    "creature",  # 2
    "enchantment",  # 3
    "instant",  # 4
    "land",  # 5
    "6",  # 6
    "7",  # 7
    "planeswalker",  # 8
    "9",  # 9
    "sorcery",  # 10
    "11",  # 11
    "12",  # 12
    "13",  # 13 dungeon?
]

missing_cards = {
    "Phil Foglio": [
        "https://scryfall.com/card/s99/7/bargain",
        "https://scryfall.com/card/2x2/359/chaos-warp",
        "https://scryfall.com/card/me3/5/cleanse",
        "https://scryfall.com/card/fem/54b/goblin-chirurgeon",
        "https://scryfall.com/card/me1/159/mirror-universe",
        "https://scryfall.com/card/atq/80a/mishras-factory",
        "https://scryfall.com/card/atq/80b/mishras-factory",
        "https://scryfall.com/card/atq/80c/mishras-factory",
        "https://scryfall.com/card/atq/80d/mishras-factory",
        "https://scryfall.com/card/leg/31/presence-of-the-master",
        "https://scryfall.com/card/por/66/prosperity",
        "https://scryfall.com/card/ugl/26/psychic-network",
        "https://scryfall.com/card/me3/168/ramirez-depietro",
    ],
    "Guru Lands": [
        "https://scryfall.com/card/pgru/1/plains",
        "https://scryfall.com/card/pgru/2/island",
        "https://scryfall.com/card/pgru/3/swamp",
        "https://scryfall.com/card/pgru/4/mountain",
        "https://scryfall.com/card/pgru/5/forest",
    ],
    "APAC/Euro Lands": [
        "https://scryfall.com/card/palp/4/plains",
        "https://scryfall.com/card/palp/10/swamp",
        "https://scryfall.com/card/palp/5/swamp",
        "https://scryfall.com/card/palp/3/mountain",
        "https://scryfall.com/card/palp/8/mountain",
        "https://scryfall.com/card/palp/6/forest",
        "https://scryfall.com/card/palp/11/forest",
        "https://scryfall.com/card/pelp/4/plains",
    ],
    "Arena League 2001-2003": [
        "https://scryfall.com/card/pal01/7/plains",
        "https://scryfall.com/card/pal01/3/island",
        "https://scryfall.com/card/pal01/9/swamp",
        "https://scryfall.com/card/pal01/1/forest",
        "https://scryfall.com/card/pal01/11/forest",
        "https://scryfall.com/card/pal02/1/island",
        "https://scryfall.com/card/pal03/3/swamp",
        "https://scryfall.com/card/pal03/5/forest",
    ],
    "Normal sets": [
        "https://scryfall.com/card/ice/371/snow-covered-island",
        "https://scryfall.com/card/csp/151/snow-covered-plains",
        "https://scryfall.com/card/usg/336/island",
        "https://scryfall.com/card/usg/345/mountain",
        "https://scryfall.com/card/mmq/331/plains",
        "https://scryfall.com/card/mmq/332/plains",
        "https://scryfall.com/card/mmq/333/plains",
        "https://scryfall.com/card/mmq/335/island",
        "https://scryfall.com/card/mmq/336/island",
        "https://scryfall.com/card/mmq/337/island",
        "https://scryfall.com/card/mmq/338/island",
        "https://scryfall.com/card/mmq/347/forest",
        "https://scryfall.com/card/mmq/348/forest",
        "https://scryfall.com/card/mmq/350/forest",
        "https://scryfall.com/card/mmq/343/mountain",
        "https://scryfall.com/card/mmq/344/mountain",
        "https://scryfall.com/card/mmq/345/mountain",
        "https://scryfall.com/card/mmq/346/mountain",
        "https://scryfall.com/card/mmq/339/swamp",
        "https://scryfall.com/card/mmq/340/swamp",
        "https://scryfall.com/card/mmq/341/swamp",
        "https://scryfall.com/card/mmq/342/swamp",
        "https://scryfall.com/card/inv/331/plains",
        "https://scryfall.com/card/inv/336/island",
        "https://scryfall.com/card/inv/337/island",
        "https://scryfall.com/card/inv/343/mountain",
        "https://scryfall.com/card/inv/345/mountain",
        "https://scryfall.com/card/inv/346/mountain",
        "https://scryfall.com/card/inv/340/swamp",
        "https://scryfall.com/card/inv/342/swamp",
        "https://scryfall.com/card/ody/331/plains",
        "https://scryfall.com/card/ody/332/plains",
        "https://scryfall.com/card/ody/333/plains",
        "https://scryfall.com/card/ody/334/plains",
        "https://scryfall.com/card/ody/336/island",
        "https://scryfall.com/card/ody/338/island",
        "https://scryfall.com/card/ody/340/swamp",
        "https://scryfall.com/card/ody/341/swamp",
        "https://scryfall.com/card/ody/342/swamp",
        "https://scryfall.com/card/ody/344/mountain",
        "https://scryfall.com/card/ody/346/mountain",
        "https://scryfall.com/card/ody/347/forest",
        "https://scryfall.com/card/ody/348/forest",
        "https://scryfall.com/card/ody/349/forest",
        "https://scryfall.com/card/ody/350/forest",
        "https://scryfall.com/card/chk/295/swamp",
        "https://scryfall.com/card/chk/297/swamp",
        "https://scryfall.com/card/chk/300/mountain",
        "https://scryfall.com/card/mrd/290/plains",
        "https://scryfall.com/card/mrd/291/island",
        "https://scryfall.com/card/mrd/292/island",
        "https://scryfall.com/card/mrd/294/island",
        "https://scryfall.com/card/mrd/295/swamp",
        "https://scryfall.com/card/mrd/297/swamp",
        "https://scryfall.com/card/mrd/301/mountain",
        "https://scryfall.com/card/mrd/305/forest",
        "https://scryfall.com/card/ons/331/plains",
        "https://scryfall.com/card/ons/340/swamp",
        "https://scryfall.com/card/ons/341/swamp",
        "https://scryfall.com/card/ons/342/swamp",
        "https://scryfall.com/card/ons/344/mountain",
        "https://scryfall.com/card/ons/345/mountain",
        "https://scryfall.com/card/ons/346/mountain",
        "https://scryfall.com/card/ons/347/forest",
        "https://scryfall.com/card/ons/348/forest",
        "https://scryfall.com/card/ons/349/forest",
        "https://scryfall.com/card/ons/350/forest",
    ],
}
