# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mtgdb', '0007_auto_20170129_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_name', models.CharField(max_length=200, verbose_name='translated name')),
                ('translated_text', models.TextField(blank=True, verbose_name='translated text')),
                ('multiverese_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='multiverse id')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgdb.Card')),
            ],
            options={
                'ordering': ('card__name', 'lang__code'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='code')),
            ],
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtglang.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='cardtranslation',
            unique_together=set([('card', 'lang')]),
        ),
    ]
