# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0007_auto_20170129_1013'),
        ('mtglang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_name', models.CharField(max_length=200, verbose_name='translated name')),
                ('multiverese_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='multiverse id')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtglang.Language')),
                ('printing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgdb.Printing')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardtranslation',
            name='multiverese_id',
        ),
        migrations.RemoveField(
            model_name='cardtranslation',
            name='translated_name',
        ),
        migrations.AlterUniqueTogether(
            name='printingtranslation',
            unique_together=set([('printing', 'lang')]),
        ),
    ]
