# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtglang', '0002_auto_20170129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtranslation',
            name='translated_name',
            field=models.CharField(default='', max_length=200, verbose_name='translated name'),
            preserve_default=False,
        ),
    ]
