# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0009_auto_20170130_1030'),
        ('mtglang', '0003_cardtranslation_translated_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulingTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField(blank=True, verbose_name='translated text')),
                ('extra_context', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='extra context')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtglang.Language', verbose_name='language')),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgdb.Ruling', verbose_name='ruling')),
            ],
        ),
        migrations.RenameField(
            model_name='printingtranslation',
            old_name='multiverese_id',
            new_name='multiverse_id',
        ),
        migrations.AddField(
            model_name='cardtranslation',
            name='extra_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='extra context'),
        ),
        migrations.AlterField(
            model_name='cardtranslation',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mtgdb.Card', verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='cardtranslation',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtglang.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtglang.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='printingtranslation',
            name='printing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgdb.Printing', verbose_name='printing'),
        ),
        migrations.AlterUniqueTogether(
            name='rulingtranslation',
            unique_together=set([('ruling', 'lang')]),
        ),
    ]
