# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtglang', '0004_auto_20170130_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtranslation',
            old_name='translated_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cardtranslation',
            old_name='translated_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='printingtranslation',
            old_name='translated_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rulingtranslation',
            old_name='translated_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='cardtranslation',
            name='extra_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extra context'),
        ),
        migrations.AlterField(
            model_name='rulingtranslation',
            name='extra_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='extra context'),
        ),
    ]
