# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtglang', '0005_auto_20170130_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printingtranslation',
            old_name='name',
            new_name='translated_name',
        ),
    ]
