# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtglang', '0006_auto_20170504_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulingtranslation',
            old_name='text',
            new_name='translated_text',
        ),
    ]
