#!/usr/bin/env python3

# proposed usage:
# ./mtgdump.py `echo $(ls ???.rst|cut -d. -f1)|sed "s/ /,/g"`

import click
import requests

from toolbox.mtg_vars import symbols_map, card_template


def reformat_card_text(text, card_name=None):
    for t, s in symbols_map.items():
        text = text.replace(t, s)
    # if card_name is not None:
    #     text = text.replace(card_name, 'this card')
    return text


@click.command()
@click.argument("expansions")
def import_rst(expansions):
    expansions = map(str.strip, expansions.split(","))
    for expansion in expansions:
        cache = []
        with open(f"{expansion}.rst", "w") as output:
            result = requests.get(f"https://api.scryfall.com/sets/{expansion.lower()}")
            if result.status_code != 200:
                print(f"ERROR retrieving expansion {expansion}!")
                continue
            name = result.json()["name"]
            result = requests.get(
                f"https://api.scryfall.com/cards/search?order=set&q=e%3A{expansion.lower()}&unique=prints"
            )
            if result.status_code != 200:
                print(f"ERROR retrieving expansion {expansion} ({name})!")
                continue
            data = result.json()
            output.write(
                f""".. {name} (autogenerated)
.. include:: symbols.rst

:mtgexp:`{expansion}` {name}
{(len(name) + len(expansion) + 12) * '='}

"""
            )
            while True:
                for card in data["data"]:
                    name = card["name"]
                    if name not in cache:
                        print(name)
                        cache.append(name)
                        if card.get("card_faces"):
                            for face in card["card_faces"]:
                                if "image_uris" in face:
                                    image_uri = face["image_uris"]["border_crop"]
                                else:
                                    image_uri = card["image_uris"]["border_crop"]
                                output.write(
                                    card_template.format(
                                        card=face,
                                        card_uri=card["scryfall_uri"],
                                        image=image_uri,
                                        card_text=reformat_card_text(
                                            face.get("oracle_text", "")
                                        ),
                                    )
                                )
                        else:
                            output.write(
                                card_template.format(
                                    card=card,
                                    card_uri=card["scryfall_uri"],
                                    image=card["image_uris"]["border_crop"],
                                    card_text=reformat_card_text(
                                        card.get("oracle_text", "")
                                    ),
                                )
                            )
                if not data["has_more"]:
                    break
                result = requests.get(data["next_page"])
                data = result.json()


if __name__ == "__main__":
    import_rst()
