
.. |M12_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |THB_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |SOM_percent| image:: images/pie40.png        

.. |SHM_percent| image:: images/pie30.png        

.. |2ED_percent| image:: images/pie50.png        

.. |GPT_percent| image:: images/pie50.png        

.. |MIR_percent| image:: images/pie25.png        

.. |CM1_percent| image:: images/pie60.png        

.. |USG_percent| image:: images/pie35.png        

.. |MRD_percent| image:: images/pie35.png        

.. |EMN_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |CHK_percent| image:: images/pie30.png        

.. |CMR_percent| image:: images/pie55.png        

.. |CMD_percent| image:: images/pie60.png        

.. |AKH_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |RIX_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |6ED_percent| image:: images/pie65.png        

.. |LRW_percent| image:: images/pie35.png        

.. |EXO_percent| image:: images/pie25.png        

.. |M13_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C20_percent| image:: images/pie65.png        

.. |BBD_percent| image:: images/pie60.png        

.. |KTK_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |M11_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |PCY_percent| image:: images/pie20.png        

.. |C18_percent| image:: images/pie65.png        

.. |BFZ_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |GRN_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |5DN_percent| image:: images/pie30.png        

.. |S99_percent| image:: images/pie60.png        

.. |STX_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C19_percent| image:: images/pie75.png        

.. |M10_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C21_percent| image:: images/pie75.png        

.. |GK1_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |XLN_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |SOK_percent| image:: images/pie15.png        

.. |DST_percent| image:: images/pie35.png        

.. |MH1_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |M14_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |TOR_percent| image:: images/pie35.png        

.. |P02_percent| image:: images/pie50.png        

.. |ATQ_percent| image:: images/pie35.png        

.. |M15_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |THS_percent| image:: images/pie95.png        

.. |MOR_percent| image:: images/pie25.png        

.. |ORI_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |TSR_percent| image:: images/pie90.png        

.. |ISD_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |DIS_percent| image:: images/pie40.png        

.. |POR_percent| image:: images/pie50.png        

.. |JMP_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |ARB_percent| image:: images/pie40.png        

.. |ALL_percent| image:: images/pie20.png        

.. |GK2_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |KLD_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |IKO_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |INV_percent| image:: images/pie30.png        

.. |WTH_percent| image:: images/pie25.png        

.. |SCG_percent| image:: images/pie40.png        

.. |TSP_percent| image:: images/pie60.png        

.. |10E_percent| image:: images/pie95.png        

.. |3ED_percent| image:: images/pie50.png        

.. |HOU_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |BOK_percent| image:: images/pie20.png        

.. |HML_percent| image:: images/pie20.png        

.. |E02_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |KHM_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |7ED_percent| image:: images/pie75.png        

.. |SOI_percent| image:: images/pie90.png        

.. |CON_percent| image:: images/pie45.png        

.. |STH_percent| image:: images/pie30.png        

.. |UDS_percent| image:: images/pie30.png        

.. |9ED_percent| image:: images/pie95.png        

.. |ROE_percent| image:: images/pie95.png        

.. |RTR_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |MMA_percent| image:: images/pie65.png        

.. |AER_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |CSP_percent| image:: images/pie30.png        

.. |C16_percent| image:: images/pie65.png        

.. |ZEN_percent| image:: images/pie35.png        

.. |A25_percent| image:: images/pie75.png        

.. |IMA_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |NPH_percent| image:: images/pie50.png        

.. |DKA_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C17_percent| image:: images/pie65.png        

.. |LEB_percent| image:: images/pie50.png        

.. |ELD_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |FRF_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |JUD_percent| image:: images/pie30.png        

.. |MBS_percent| image:: images/pie40.png        

.. |PLS_percent| image:: images/pie30.png        

.. |WWK_percent| image:: images/pie40.png        

.. |OGW_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C15_percent| image:: images/pie65.png        

.. |GNT_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |RNA_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |EMA_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |BNG_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C14_percent| image:: images/pie60.png        

.. |LEA_percent| image:: images/pie50.png        

.. |JOU_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |LGN_percent| image:: images/pie25.png        

.. |5ED_percent| image:: images/pie45.png        

.. |DGM_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |2XM_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |ZNC_percent| image:: images/pie80.png        

.. |DTK_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |M21_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |FEM_percent| image:: images/pie10.png        

.. |APC_percent| image:: images/pie30.png        

.. |EVE_percent| image:: images/pie30.png        

.. |S00_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |M19_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |MMQ_percent| image:: images/pie25.png        

.. |MM3_percent| image:: images/pie95.png        

.. |VIS_percent| image:: images/pie30.png        

.. |TMP_percent| image:: images/pie35.png        

.. |CN2_percent| image:: images/pie50.png        

.. |AVR_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |FUT_percent| image:: images/pie55.png        

.. |KHC_percent| image:: images/pie70.png        

.. |ONS_percent| image:: images/pie30.png        

.. |MM2_percent| image:: images/pie75.png        

.. |4ED_percent| image:: images/pie45.png        

.. |M20_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |C13_percent| image:: images/pie60.png        

.. |WAR_percent| image:: images/pie95.png        

.. |RAV_percent| image:: images/pie50.png        

.. |8ED_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |DRK_percent| image:: images/pie20.png        

.. |ALA_percent| image:: images/pie45.png        

.. |ICE_percent| image:: images/pie20.png        

.. |NEM_percent| image:: images/pie20.png        

.. |CNS_percent| image:: images/pie55.png        

.. |ULG_percent| image:: images/pie40.png        

.. |ODY_percent| image:: images/pie35.png        

.. |ZNR_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |DOM_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |PLC_percent| image:: images/pie55.png        

.. |GTC_percent| image:: images/done.png        
   :alt: Tłumaczenie zakończone

.. |ARN_percent| image:: images/pie25.png        

.. |PTK_percent| image:: images/pie35.png        

.. |UMA_percent| image:: images/pie95.png        

.. |LEG_percent| image:: images/pie20.png        
