# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expansion',
            name='border',
            field=models.CharField(blank=True, choices=[('b', 'Black'), ('w', 'White'), ('s', 'Silver'), ('g', 'Gold')], max_length=1, verbose_name='border'),
        ),
    ]
