# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0003_auto_20170128_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='source',
            field=models.CharField(blank=True, max_length=256, verbose_name='source'),
        ),
    ]
