# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0004_auto_20170128_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.PositiveIntegerField(default=0, verbose_name='cmc'),
        ),
    ]
