# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0005_auto_20170128_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsubtype',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cardsupertype',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cardtype',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='name'),
        ),
    ]
