# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0006_auto_20170128_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=100, verbose_name='mana cost'),
        ),
    ]
