# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0008_auto_20170129_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expansion',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='printing',
            options={'ordering': ['-expansion__release_date', 'number']},
        ),
        migrations.AlterModelOptions(
            name='ruling',
            options={'ordering': ['date']},
        ),
    ]
