# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0010_auto_20170130_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='mtgdb.CardSubtype', verbose_name='subtypes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='supertypes',
            field=models.ManyToManyField(blank=True, to='mtgdb.CardSupertype', verbose_name='supertypes'),
        ),
    ]
