# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgdb', '0011_auto_20170130_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='printing',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
    ]
